version: "3.9"

services:
  gemma-dietbot:
    container_name: gemma3-1b-dietbot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODEL_ID: jshargo/gemma-3N-finetune-4B
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_MODEL=jshargo/gemma-3N-finetune-4B
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped