# docker-compose.yml
services:
  app:
    container_name: dietbot_app
    build: .
    ports:
      - "8001:8001"
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      NUTRITIONIX_APP_ID: ${NUTRITIONIX_APP_ID}
      NUTRITIONIX_API_KEY: ${NUTRITIONIX_API_KEY}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-dietbot}
      OLLAMA_API_URL: http://host.docker.internal:11434/api/chat
    volumes:
      - .:/app
    command: >
      sh -c "echo 'Starting Uvicorn on port 8001...' &&
             uvicorn dietbot.main:app --host 0.0.0.0 --port 8001 --reload"

volumes: {}
